# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # Prevent giant files from being committed
    -   id: check-added-large-files
        args: ['--maxkb=512']
    # Simply check whether files parse as valid python
    -   id: check-ast
    # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
    -   id: check-case-conflict
    # Checks for a common error of placing code before the docstring
    -   id:     check-docstring-first
    # Check for files that contain merge conflict strings
    -   id: check-merge-conflict
    # Checks for symlinks which do not point to anything
    -   id: check-symlinks
    # Attempts to load all yaml files to verify syntax
    -   id: check-yaml
    # Makes sure files end in a newline and only a newline
    -   id: end-of-file-fixer

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.4'
    hooks:
    -   id: autopep8
        args: ['-i', '--max-line-length', '120']
